apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: world-pipeline-run-
  namespace: argo
spec:
  workflowTemplateRef:
    name: world-pipeline

  arguments:
    parameters:
      - name: cluster
      - name: region
        value: "us-east-1"
      - name: imageRepo
      - name: worldName
      - name: worldId
      - name: logLocation
        value: "logs"
      - name: version
        value: "2.2.11"
      - name: retryCount
        value: 2
      - name: worldInfoLocation
